version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: pocdb
      POSTGRES_USER: pocuser
      POSTGRES_PASSWORD: pocpass
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
